version: '3.0'

services:

  api:
    build: .
    env_file:
      - .env
    ports:
      - '8080:8080'

  postgres:
    image: 'postgres:16.1'
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/init-schema.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: 'bitnami/minio:2024.3.15'
    container_name: minio-node-1
    env_file:
      - .env
    ports:
      - '9005:9001'
      - '9004:9000'
    volumes:
      - minio-data:/bitnami/minio/data

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local