spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/waceplare
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
server:
  error:
    include-message: always
upload:
  path: E:/Images/
