spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
server:
  error:
    include-message: always
upload:
  path: E:/Images/
