spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/waceplare
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github: