spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  liquibase:
    enabled: true
    liquibase-schema: migration_schema
    default-schema: main_schema
minio:
  bucket: ${MINIO_DEFAULT_BUCKETS}
  username: ${MINIO_ROOT_USER}
  password: ${MINIO_ROOT_PASSWORD}
  url: http://localhost:9004

server:
  error:
    include-message: always
